[project]
name = "pubsub"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mypy>=1.13.0",
    "websockets>=13.1",
]

[tools.mypy]
strict = true
